-- Redfin MN County Table
CREATE TABLE redfin_mn_county (
    period_begin                    DATE,
    period_end                      DATE,
    period_duration                 INT,
    region_type                     VARCHAR(50),
    region_type_id                  INT,
    table_id                        INT,
    is_seasonally_adjusted          VARCHAR(10),
    region                          VARCHAR(100),
    city                            VARCHAR(100),
    state                           VARCHAR(50),
    state_code                      VARCHAR(5),
    property_type                   VARCHAR(50),
    property_type_id                INT,
    median_sale_price               NUMERIC(12,2),
    median_sale_price_mom           NUMERIC(12,2),
    median_sale_price_yoy           NUMERIC(12,2),
    median_list_price               NUMERIC(12,2),
    median_list_price_mom           NUMERIC(12,2),
    median_list_price_yoy           NUMERIC(12,2),
    median_ppsf                     NUMERIC(10,2),
    median_ppsf_mom                 NUMERIC(10,2),
    median_ppsf_yoy                 NUMERIC(10,2),
    median_list_ppsf                NUMERIC(10,2),
    median_list_ppsf_mom            NUMERIC(10,2),
    median_list_ppsf_yoy            NUMERIC(10,2),
    homes_sold                      NUMERIC(10,2),
    homes_sold_mom                  NUMERIC(10,2),
    homes_sold_yoy                  NUMERIC(10,2),
    pending_sales                   NUMERIC(10,2),
    pending_sales_mom               NUMERIC(10,2),
    pending_sales_yoy               NUMERIC(10,2),
    new_listings                    NUMERIC(10,2),
    new_listings_mom                NUMERIC(10,2),
    new_listings_yoy                NUMERIC(10,2),
    inventory                       NUMERIC(10,2),
    inventory_mom                   NUMERIC(10,2),
    inventory_yoy                   NUMERIC(10,2),
    months_of_supply                NUMERIC(10,2),
    months_of_supply_mom            NUMERIC(10,2),
    months_of_supply_yoy            NUMERIC(10,2),
    median_dom                      NUMERIC(10,2),
    median_dom_mom                  NUMERIC(10,2),
    median_dom_yoy                  NUMERIC(10,2),
    avg_sale_to_list                NUMERIC(10,4),
    avg_sale_to_list_mom            NUMERIC(10,4),
    avg_sale_to_list_yoy            NUMERIC(10,4),
    sold_above_list                 NUMERIC(10,4),
    sold_above_list_mom             NUMERIC(10,4),
    sold_above_list_yoy             NUMERIC(10,4),
    price_drops                     NUMERIC(10,4),
    price_drops_mom                 NUMERIC(10,4),
    price_drops_yoy                 NUMERIC(10,4),
    off_market_in_two_weeks         NUMERIC(10,4),
    off_market_in_two_weeks_mom     NUMERIC(10,4),
    off_market_in_two_weeks_yoy     NUMERIC(10,4),
    parent_metro_region             VARCHAR(100),
    parent_metro_region_metro_code  VARCHAR(20),
    last_updated                    DATE
);

-- Zillow ZHVI MN County Table
CREATE TABLE zillow_zhvi_mn_county (
    region_id           INT,
    size_rank           INT,
    region_name         VARCHAR(100),
    region_type         VARCHAR(50),
    state_name          VARCHAR(50),
    state               VARCHAR(5),
    metro               VARCHAR(100),
    state_code_fips     VARCHAR(5),
    municipal_code_fips VARCHAR(10),
    period_date         VARCHAR(20),
    home_value          NUMERIC(12,2)
);